/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const extensions: () => [number, number];
export const fromHtml: (a: number, b: number, c: number, d: number) => [number, number, number];
export const fromMarkdown: (a: number, b: number) => [number, number, number];
export const parseJson: (a: number, b: number) => [number, number];
export const toAnsi: (a: number, b: number) => [number, number];
export const toAnsiWithReport: (a: number, b: number, c: number, d: number) => [number, number, number];
export const toCarve: (a: number, b: number) => [number, number];
export const toCarveWithReport: (a: number, b: number, c: number, d: number) => [number, number, number];
export const toHtml: (a: number, b: number) => [number, number];
export const toHtmlFull: (a: number, b: number, c: number) => [number, number, number, number];
export const toHtmlWithOptions: (a: number, b: number, c: number) => [number, number, number, number];
export const toHtmlWithReport: (a: number, b: number, c: number, d: number) => [number, number, number];
export const toHtmlWithSymbols: (a: number, b: number, c: number) => [number, number, number, number];
export const toMarkdown: (a: number, b: number) => [number, number];
export const toMarkdownWithReport: (a: number, b: number, c: number, d: number) => [number, number, number];
export const toPlainText: (a: number, b: number) => [number, number];
export const toPlainTextWithReport: (a: number, b: number, c: number, d: number) => [number, number, number];
export const version: () => [number, number];
export const htmlToCarve: (a: number, b: number, c: number, d: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
